import Navbar from '@/components/Navbar/Navbar'
import './globals.css'
import AuthProvider from '@/components/AuthProvider/AuthProvider'
import NextTopLoader from 'nextjs-toploader';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <NextTopLoader color='#000000'/>
        <AuthProvider>
          <main className='min-h-screen mx-4 md:mx-24'>
            <Navbar/>
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  )
}
